Repository codesquad-masters2024-team09/issue-tracker, pull requests merged in 2024-05, with the labels that each got.

#3 [Feat/#1] 이슈 등록 기능 구현
  build.gradle
  src/main/java/com/issuetracker/domain/common/BaseDateTime.java
  src/main/java/com/issuetracker/domain/issue/Issue.java
  src/main/java/com/issuetracker/domain/issue/IssueController.java
  src/main/java/com/issuetracker/domain/issue/IssueRepository.java
  src/main/java/com/issuetracker/domain/issue/IssueService.java
  src/main/java/com/issuetracker/domain/issue/request/IssueCreateRequest.java
  src/main/java/com/issuetracker/domain/member/Member.java
  src/main/java/com/issuetracker/domain/member/MemberRepository.java
  src/main/java/com/issuetracker/global/config/JdbcConfig.java
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/main/resources/data.sql
  src/main/resources/schema.sql
  src/test/java/com/issuetracker/domain/issue/IssueControllerTest.java
  src/test/java/com/issuetracker/domain/issue/IssueTest.java
  src/test/java/com/issuetracker/domain/member/MemberTest.java
Labels: feature, 담당: yelly, 담당: sharpie, 담당: sid

#6 [Feat/#2] 이슈 등록 Controller 테스트 실패 문제 해결
  src/test/java/com/issuetracker/domain/issue/IssueControllerTest.java
Labels: fix, 담당: sharpie

#9 [Feat/#4] 이슈 수정 기능 구현
  build.gradle
  src/main/java/com/issuetracker/domain/issue/IssueController.java
  src/main/java/com/issuetracker/domain/issue/IssueMapper.java
  src/main/java/com/issuetracker/domain/issue/IssueService.java
  src/main/java/com/issuetracker/domain/issue/request/IssueUpdateRequest.java
  src/main/resources/application.yml
  src/main/resources/mapper/issue/Issue.xml
  src/test/java/com/issuetracker/domain/issue/IssueControllerTest.java
  src/test/java/com/issuetracker/domain/issue/request/IssueUpdateRequestTest.java
Labels: feature, 담당: yelly

#10 [Feat/#5] 이슈 상세 조회 기능 구현
  src/main/java/com/issuetracker/domain/issue/IssueController.java
  src/main/java/com/issuetracker/domain/issue/IssueService.java
  src/main/java/com/issuetracker/domain/issue/response/IssueDetailResponse.java
  src/test/java/com/issuetracker/domain/issue/IssueControllerTest.java
Labels: feature

#11 Feat/#7 이슈 등록 시 입력 데이터 유효성 검증, 테스트 코드 작성
  src/main/java/com/issuetracker/domain/issue/request/IssueCreateRequest.java
  src/main/java/com/issuetracker/global/config/WebConfig.java
  src/main/resources/application.yml
  src/main/resources/templates/issue/addIssue.html
  src/test/java/com/issuetracker/domain/issue/IssueControllerTest.java
Labels: feature, 담당: sharpie

#12 [Feat/#8] 이슈 삭제 기능 구현
  src/main/java/com/issuetracker/domain/issue/IssueController.java
  src/main/java/com/issuetracker/domain/issue/IssueService.java
  src/test/java/com/issuetracker/domain/issue/IssueControllerTest.java
Labels: feature, 담당: sid

#17 [Feat/#15] 댓글 생성, 삭제, 수정 및 이슈 조회 시 댓글 조회 기능 구현
  src/main/java/com/issuetracker/domain/comment/Comment.java
  src/main/java/com/issuetracker/domain/comment/CommentController.java
  src/main/java/com/issuetracker/domain/comment/CommentRepository.java
  src/main/java/com/issuetracker/domain/comment/CommentService.java
  src/main/java/com/issuetracker/domain/comment/request/CommentCreateRequest.java
  src/main/java/com/issuetracker/domain/comment/request/CommentUpdateRequest.java
  src/main/java/com/issuetracker/domain/comment/response/CommentUpdateResponse.java
  src/main/java/com/issuetracker/domain/common/LocalDateTimeToStringConverter.java
  src/main/java/com/issuetracker/domain/issue/Issue.java
  src/main/java/com/issuetracker/domain/issue/response/IssueDetailResponse.java
  src/main/resources/schema.sql
  src/test/java/com/issuetracker/domain/comment/request/CommentCreateRequestTest.java
  src/test/java/com/issuetracker/domain/comment/request/CommentUpdateRequestTest.java
  src/test/java/com/issuetracker/domain/common/LocalDateTimeToStringConverterTest.java
Labels: feature, 담당: yelly

#20 [Feat/#16] 마일스톤 기능 구현
  src/main/java/com/issuetracker/domain/milestone/Milestone.java
  src/main/java/com/issuetracker/domain/milestone/MilestoneController.java
  src/main/java/com/issuetracker/domain/milestone/MilestoneMapper.java
  src/main/java/com/issuetracker/domain/milestone/MilestoneRepository.java
  src/main/java/com/issuetracker/domain/milestone/MilestoneService.java
  src/main/java/com/issuetracker/domain/milestone/request/MilestoneCreateRequest.java
  src/main/java/com/issuetracker/domain/milestone/request/MilestoneUpdateRequest.java
  src/main/java/com/issuetracker/domain/milestone/response/MilestoneListResponse.java
  src/main/java/com/issuetracker/domain/milestone/response/MilestoneResponse.java
  src/main/resources/data.sql
  src/main/resources/mapper/milestone/milestone.xml
  src/main/resources/schema.sql
  src/test/java/com/issuetracker/domain/milestone/MilestoneControllerTest.java
  src/test/java/com/issuetracker/domain/milestone/MilestoneTest.java
Labels: feature

#21 [fe-init] 프론트엔드 initial commit
  frontend/.gitignore
  frontend/README.md
  frontend/index.html
  frontend/jsconfig.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.svelte
  frontend/src/assets/logo.svg
  frontend/src/components/comment/Comment.svelte
  frontend/src/components/comment/CommentAddForm.svelte
  frontend/src/components/comment/CommentEditForm.svelte
  frontend/src/components/common/Header.svelte
  frontend/src/components/common/Loading.svelte
  frontend/src/components/issue/Issue.svelte
  frontend/src/components/issue/IssueAddForm.svelte
  frontend/src/components/issue/IssueAssignOption.svelte
  frontend/src/components/issue/IssueList.svelte
  frontend/src/components/issue/IssuePreview.svelte
  frontend/src/components/issue/IssueTitleEditForm.svelte
  frontend/src/components/label/LabelAddForm.svelte
  frontend/src/components/label/LabelEditForm.svelte
  frontend/src/components/label/LabelList.svelte
  frontend/src/components/label/LabelPreview.svelte
  frontend/src/components/milestone/MilestoneAddForm.svelte
  frontend/src/components/milestone/MilestoneEditForm.svelte
  frontend/src/components/milestone/MilestoneList.svelte
  frontend/src/components/milestone/MilestonePreview.svelte
  frontend/src/components/part/LabelMilstoneNavTab.svelte
  frontend/src/components/part/OptionBox.svelte
  frontend/src/components/part/OptionPopup.svelte
  frontend/src/main.js
  frontend/src/pages/issue/IssueAddPage.svelte
  frontend/src/pages/issue/IssueDetailPage.svelte
  frontend/src/pages/issue/IssueListPage.svelte
  frontend/src/pages/label/LabelPage.svelte
  frontend/src/pages/milestone/MilestonePage.svelte
  frontend/src/route.svelte
  frontend/src/service/api.js
  frontend/src/style/main.css
  frontend/src/vite-env.d.ts
  frontend/svelte.config.js
  frontend/vite.config.js
Labels: feature, 담당: sharpie, 담당: sid

#25 [Feat/#23] 연관관계 매핑 구현
  src/main/java/com/issuetracker/domain/comment/Comment.java
  src/main/java/com/issuetracker/domain/comment/CommentService.java
  src/main/java/com/issuetracker/domain/issue/Issue.java
  src/main/java/com/issuetracker/domain/issue/IssueLabel.java
  src/main/java/com/issuetracker/domain/issue/IssueRepository.java
  src/main/java/com/issuetracker/domain/issue/IssueService.java
  src/main/java/com/issuetracker/domain/issue/response/IssueListResponse.java
  src/main/java/com/issuetracker/domain/issue/response/IssueResponse.java
  src/main/java/com/issuetracker/domain/label/Label.java
  src/main/java/com/issuetracker/domain/label/LabelRepository.java
  src/main/java/com/issuetracker/domain/label/LabelService.java
  src/main/java/com/issuetracker/domain/member/Member.java
  src/main/java/com/issuetracker/domain/milestone/Milestone.java
  src/main/java/com/issuetracker/domain/milestone/MilestoneController.java
  src/main/java/com/issuetracker/domain/milestone/MilestoneRepository.java
  src/main/java/com/issuetracker/domain/milestone/MilestoneService.java
  src/main/java/com/issuetracker/domain/milestone/argumentresolver/MilestoneId.java
  src/main/java/com/issuetracker/domain/milestone/argumentresolver/MilestoneIdArgumentResolver.java
  src/main/java/com/issuetracker/domain/milestone/request/MilestoneCreateRequest.java
  src/main/java/com/issuetracker/domain/milestone/request/MilestoneUpdateRequest.java
  src/main/java/com/issuetracker/domain/milestone/response/MilestoneResponse.java
  src/main/java/com/issuetracker/global/config/WebConfig.java
  src/main/resources/data.sql
  src/main/resources/mapper/milestone/milestone.xml
  src/main/resources/schema.sql
  src/test/java/com/issuetracker/domain/issue/IssueTest.java
  src/test/java/com/issuetracker/domain/label/LabelControllerTest.java
  src/test/java/com/issuetracker/domain/milestone/MilestoneControllerTest.java
  src/test/java/com/issuetracker/domain/milestone/MilestoneTest.java
Labels: feature

#30 Feat/#26 이슈 등록 시 레이블과 마일스톤 함께 등록, 이슈에 레이블 추가, 이슈에 마일스톤 추가 구현
  src/main/java/com/issuetracker/domain/comment/Comment.java
  src/main/java/com/issuetracker/domain/comment/request/CommentCreateRequest.java
  src/main/java/com/issuetracker/domain/issue/IssueController.java
  src/main/java/com/issuetracker/domain/issue/IssueService.java
  src/main/java/com/issuetracker/domain/issue/request/IssueCreateRequest.java
  src/main/java/com/issuetracker/domain/issue/request/IssueLabelCreateRequest.java
  src/main/java/com/issuetracker/domain/issue/request/IssueMilestoneCreateRequest.java
  src/test/java/com/issuetracker/domain/issue/IssueControllerTest.java
  src/test/java/com/issuetracker/domain/issue/IssueTest.java
Labels: feature, 담당: sharpie

#34 [Feat/#32] 엔터티 연관관계 매핑 관련 컨트롤러, 서비스 수정 작업 완료
  src/main/java/com/issuetracker/domain/issue/Issue.java
  src/main/java/com/issuetracker/domain/issue/IssueController.java
  src/main/java/com/issuetracker/domain/issue/IssueLabel.java
  src/main/java/com/issuetracker/domain/issue/IssueService.java
  src/main/java/com/issuetracker/domain/issue/request/IssueCreateRequest.java
  src/main/java/com/issuetracker/domain/issue/request/IssueUpdateRequest.java
  src/main/java/com/issuetracker/domain/issue/request/LabelAddRequest.java
  src/main/java/com/issuetracker/domain/issue/request/MilestoneAssignRequest.java
  src/main/resources/schema.sql
  src/test/java/com/issuetracker/domain/issue/IssueControllerTest.java
  src/test/java/com/issuetracker/domain/issue/IssueTest.java
Labels: feature

#31 [fix/#28] fix: 댓글 추가 시 생성 시간 초기화 수정 완료
  src/main/java/com/issuetracker/domain/comment/Comment.java
  src/main/java/com/issuetracker/domain/common/BaseDateTime.java
  src/main/java/com/issuetracker/domain/issue/Issue.java
Labels: fix

#36 [Feat/#24] 이슈 상세 조회 화면 구현
  frontend/index.html
  frontend/public/assets/issue_icon_black.svg
  frontend/public/assets/issue_icon_blue.svg
  frontend/public/assets/issue_icon_closed.svg
  frontend/public/assets/logo.svg
  frontend/public/assets/profile_icon.svg
  frontend/public/assets/profile_icon_duck.svg
  frontend/public/assets/toggle_btn.svg
  frontend/src/App.svelte
  frontend/src/components/common/Header.svelte
  frontend/src/components/common/Loading.svelte
  frontend/src/pages/issue/IssueAddPage.svelte
  frontend/src/pages/issue/IssueDetailPage.svelte
  frontend/src/route.svelte
  frontend/src/stores/issue.js
  frontend/src/style/main.css
  frontend/src/utils/constants.js
  src/main/java/com/issuetracker/global/config/WebConfig.java
  src/main/resources/templates/issues/detail.html
Labels: feature, 담당: sid

#39 [Feat/#35] 이슈 필터 및 검색 기능 구현
  src/main/java/com/issuetracker/domain/issue/AggregateReferenceTypeHandler.java
  src/main/java/com/issuetracker/domain/issue/Issue.java
  src/main/java/com/issuetracker/domain/issue/IssueController.java
  src/main/java/com/issuetracker/domain/issue/IssueLabelMapper.java
  src/main/java/com/issuetracker/domain/issue/IssueMapper.java
  src/main/java/com/issuetracker/domain/issue/IssueService.java
  src/main/java/com/issuetracker/domain/issue/request/IssueSearchCondition.java
  src/main/java/com/issuetracker/domain/issue/response/IssueResponse.java
  src/main/java/com/issuetracker/domain/issue/util/IssueQueryParser.java
  src/main/java/com/issuetracker/domain/milestone/MilestoneMapper.java
  src/main/java/com/issuetracker/domain/milestone/argumentresolver/MilestoneIdArgumentResolver.java
  src/main/resources/application.yml
  src/main/resources/mapper/issue/Issue.xml
  src/main/resources/mapper/issue/issueLabel.xml
  src/main/resources/mapper/milestone/milestone.xml
  src/test/java/com/issuetracker/domain/issue/IssueTest.java
  src/test/java/com/issuetracker/domain/issue/argumentresolver/IssueQueryParserTest.java
Labels: feature

#42 Feat/#38 예외처리 로직 구현
  src/main/java/com/issuetracker/domain/comment/CommentService.java
  src/main/java/com/issuetracker/domain/issue/IssueService.java
  src/main/java/com/issuetracker/domain/label/LabelService.java
  src/main/java/com/issuetracker/domain/milestone/MilestoneService.java
  src/main/java/com/issuetracker/domain/milestone/argumentresolver/MilestoneIdArgumentResolver.java
  src/main/java/com/issuetracker/global/exception/ErrorResponse.java
  src/main/java/com/issuetracker/global/exception/ExceptionType.java
  src/main/java/com/issuetracker/global/exception/GlobalException.java
  src/main/java/com/issuetracker/global/exception/GlobalExceptionHandler.java
  src/main/java/com/issuetracker/global/exception/ValidationErrorDetails.java
  src/main/java/com/issuetracker/global/exception/ValidationErrorResponse.java
  src/main/java/com/issuetracker/global/exception/comment/CommentNotFoundException.java
  src/main/java/com/issuetracker/global/exception/common/BadRequestException.java
  src/main/java/com/issuetracker/global/exception/common/ConflictException.java
  src/main/java/com/issuetracker/global/exception/common/InternalServerErrorException.java
  src/main/java/com/issuetracker/global/exception/common/NotFoundException.java
  src/main/java/com/issuetracker/global/exception/issue/IssueDuplicationException.java
  src/main/java/com/issuetracker/global/exception/issue/IssueNotFoundException.java
  src/main/java/com/issuetracker/global/exception/label/LabelDuplicateException.java
  src/main/java/com/issuetracker/global/exception/label/LabelNotFoundException.java
  src/main/java/com/issuetracker/global/exception/member/MemberDuplicateException.java
  src/main/java/com/issuetracker/global/exception/member/MemberNotFoundException.java
  src/main/java/com/issuetracker/global/exception/milestone/MilestoneDuplicateException.java
  src/main/java/com/issuetracker/global/exception/milestone/MilestoneNotFoundException.java
Labels: feature, 담당: sharpie

#46 Feat/#22 레이블 화면 구현, CRUD api 연결
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/label/LabelAddForm.svelte
  frontend/src/components/label/LabelEditForm.svelte
  frontend/src/components/label/LabelList.svelte
  frontend/src/components/label/LabelPreview.svelte
  frontend/src/pages/label/LabelPage.svelte
  frontend/src/service/api.js
  frontend/src/store/label.js
  frontend/src/style/main.css
  frontend/src/utils/color.js
  frontend/src/utils/validates.js
Labels: feature, 담당: sharpie

#47 Feat/#43 이슈 상세 조회 기능 구현
  src/main/java/com/issuetracker/domain/comment/response/CommentResponse.java
  src/main/java/com/issuetracker/domain/issue/IssueController.java
  src/main/java/com/issuetracker/domain/issue/IssueDetails.java
  src/main/java/com/issuetracker/domain/issue/IssueService.java
  src/main/java/com/issuetracker/domain/issue/IssueViewMapper.java
  src/main/java/com/issuetracker/domain/issue/response/IssueDetailResponse.java
  src/main/java/com/issuetracker/domain/issue/response/IssueDetailsResponse.java
  src/main/resources/mapper/issue/IssueDetails.xml
  src/test/java/com/issuetracker/domain/issue/IssueControllerTest.java
Labels: feature, 담당: sharpie

#49 [Feat/#37] 이슈 목록, 상세조회, 작성 화면, 팝업 필터 화면 작업
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/postcss.config.js
  frontend/public/assets/label_icon.svg
  frontend/public/assets/milestone_icon.svg
  frontend/src/App.svelte
  frontend/src/app.css
  frontend/src/components/common/Header.svelte
  frontend/src/components/issue/FilterOptions.svelte
  frontend/src/components/issue/Issue.svelte
  frontend/src/components/issue/IssueFilterOptionButtons.svelte
  frontend/src/components/issue/IssueList.svelte
  frontend/src/components/issue/IssueLoading.svelte
  frontend/src/components/issue/NoIssue.svelte
  frontend/src/components/part/OptionPopup.svelte
  frontend/src/components/part/PopupOption.svelte
  frontend/src/main.js
  frontend/src/pages/issue/IssueAddPage.svelte
  frontend/src/pages/issue/IssueDetailPage.svelte
  frontend/src/pages/issue/IssueListPage.svelte
  frontend/src/pages/issue/Issues.svelte
  frontend/src/route.svelte
  frontend/src/routes/+layout.svelte
  frontend/src/service/buttonSelection.js
  frontend/src/stores/filter.js
  frontend/src/stores/issue.js
  frontend/src/utils/constants.js
  frontend/tailwind.config.js
  src/main/java/com/issuetracker/global/config/WebConfig.java
Labels: feature, frontend

#53 [fix/#52] fix: gradle 빌드 시 에러 발생 코드 수정
  src/main/java/com/issuetracker/domain/comment/Comment.java
  src/main/java/com/issuetracker/domain/comment/CommentRepository.java
  src/main/java/com/issuetracker/domain/issue/Issue.java
  src/main/java/com/issuetracker/domain/label/Label.java
  src/main/java/com/issuetracker/domain/member/Member.java
  src/main/java/com/issuetracker/domain/milestone/Milestone.java
Labels: fix

#56 [Fix/#55] PR#49 누락분 추가, 타임리프 모듈 제거, 스벨트 레이블 스토어 폴더 이동
  build.gradle
  frontend/package-lock.json
  frontend/src/app.css
  frontend/src/components/common/Header.svelte
  frontend/src/components/common/LabelMilestoneNavtab.svelte
  frontend/src/components/issue/IssueEditContentForm.svelte
  frontend/src/components/issue/IssueEditTitleForm.svelte
  frontend/src/components/issue/IssueItem.svelte
  frontend/src/components/issue/IssueList.svelte
  frontend/src/components/issue/NoIssue.svelte
  frontend/src/components/label/LabelAddForm.svelte
  frontend/src/components/label/LabelEditForm.svelte
  frontend/src/components/label/LabelList.svelte
  frontend/src/components/label/LabelPreview.svelte
  frontend/src/pages/issue/IssueAddPage.svelte
  frontend/src/pages/issue/IssueDetailPage.svelte
  frontend/src/pages/issue/IssueListPage.svelte
  frontend/src/pages/issue/Issues.svelte
  frontend/src/pages/label/LabelPage.svelte
  frontend/src/stores/issue.js
  frontend/src/stores/label.js
  src/main/java/com/issuetracker/domain/issue/response/IssueResponse.java
  src/main/resources/application.yml
  src/main/resources/mapper/issue/Issue.xml
  src/main/resources/templates/issue/addIssue.html
  src/main/resources/templates/issues/detail.html
Labels: fix

#57 [Fix/#54] 마일스톤 수정 시 원래 있던 값을 빈 값으로 바꿀 때 null이 문제되는 현상 수정
  src/main/java/com/issuetracker/domain/milestone/MilestoneController.java
  src/main/java/com/issuetracker/domain/milestone/MilestoneMapper.java
  src/main/java/com/issuetracker/domain/milestone/MilestoneRepository.java
  src/main/java/com/issuetracker/domain/milestone/MilestoneService.java
  src/main/resources/mapper/milestone/milestone.xml
  src/test/java/com/issuetracker/domain/milestone/MilestoneControllerTest.java
Labels: fix, 담당: sid

#48 Feat/#45 마일스톤 CRUD 화면 구현, 서버와 api 연결 작업
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/milestone/MilestoneAddForm.svelte
  frontend/src/components/milestone/MilestoneEditForm.svelte
  frontend/src/components/milestone/MilestoneList.svelte
  frontend/src/components/milestone/MilestonePreview.svelte
  frontend/src/pages/milestone/MilestonePage.svelte
  frontend/src/stores/milestone.js
  frontend/src/utils/validates.js
  src/main/java/com/issuetracker/domain/milestone/Milestone.java
  src/main/java/com/issuetracker/domain/milestone/MilestoneRepository.java
  src/main/java/com/issuetracker/domain/milestone/MilestoneService.java
  src/main/java/com/issuetracker/domain/milestone/request/MilestoneCreateRequest.java
  src/main/java/com/issuetracker/domain/milestone/request/MilestoneUpdateRequest.java
  src/main/java/com/issuetracker/domain/milestone/response/MilestoneResponse.java
  src/test/java/com/issuetracker/domain/milestone/MilestoneControllerTest.java
  src/test/java/com/issuetracker/domain/milestone/MilestoneTest.java
Labels: feature, 담당: sharpie

#61 [Feat/#50] 레이블 프론트엔드 작업 및 버그 수정
  frontend/src/app.css
  frontend/src/components/common/LabelMilestoneNavtab.svelte
  frontend/src/components/issue/IssueEditContentForm.svelte
  frontend/src/components/issue/IssueEditTitleForm.svelte
  frontend/src/components/label/LabelAddForm.svelte
  frontend/src/components/label/LabelEditForm.svelte
  frontend/src/components/label/LabelList.svelte
  frontend/src/components/label/LabelPreview.svelte
  frontend/src/components/label/NoLabel.svelte
  frontend/src/pages/issue/IssueAddPage.svelte
  frontend/src/pages/issue/IssueDetailPage.svelte
  frontend/src/pages/label/LabelPage.svelte
  frontend/src/route.svelte
  frontend/tailwind.config.js
  src/main/java/com/issuetracker/domain/label/LabelController.java
  src/main/java/com/issuetracker/domain/label/LabelService.java
  src/main/java/com/issuetracker/domain/label/request/LabelUpdateRequest.java
  src/main/resources/mapper/label/label.xml
Labels: feature, fix

#60 [Feat/#51] 회원가입, 로그인, 로그아웃, 토큰 발급, 재발급 구현
  build.gradle
  src/main/java/com/issuetracker/domain/member/AuthController.java
  src/main/java/com/issuetracker/domain/member/Member.java
  src/main/java/com/issuetracker/domain/member/MemberController.java
  src/main/java/com/issuetracker/domain/member/MemberRepository.java
  src/main/java/com/issuetracker/domain/member/MemberService.java
  src/main/java/com/issuetracker/domain/member/request/IdDuplicateCheckRequest.java
  src/main/java/com/issuetracker/domain/member/request/LoginRequest.java
  src/main/java/com/issuetracker/domain/member/request/LogoutRequest.java
  src/main/java/com/issuetracker/domain/member/request/SignUpRequest.java
  src/main/java/com/issuetracker/domain/member/response/AuthResponse.java
  src/main/java/com/issuetracker/domain/member/response/DuplicateCheckResponse.java
  src/main/java/com/issuetracker/global/config/AuthConfig.java
  src/main/java/com/issuetracker/global/config/WebConfig.java
  src/main/java/com/issuetracker/global/exception/ExceptionType.java
  src/main/java/com/issuetracker/global/exception/common/UnauthorizedException.java
  src/main/java/com/issuetracker/global/exception/member/InvalidLoginDataException.java
  src/main/java/com/issuetracker/global/exception/member/InvalidTokenException.java
  src/main/java/com/issuetracker/global/exception/member/TokenExpiredException.java
  src/main/java/com/issuetracker/global/exception/member/TokenNotExistException.java
  src/main/java/com/issuetracker/global/security/AuthTokenInterceptor.java
  src/main/java/com/issuetracker/global/security/JwtTokenProvider.java
  src/main/java/com/issuetracker/global/security/PasswordEncoder.java
  src/main/resources/application.yml
  src/main/resources/schema.sql
Labels: feature, 담당: sharpie

#62 [Feat/#58] 마일스톤의 이슈 진행률 계산 api 추가
  src/main/java/com/issuetracker/domain/issue/IssueDetails.java
  src/main/java/com/issuetracker/domain/issue/response/IssueDetailsResponse.java
  src/main/java/com/issuetracker/domain/milestone/MilestoneController.java
  src/main/java/com/issuetracker/domain/milestone/MilestoneDetails.java
  src/main/java/com/issuetracker/domain/milestone/MilestoneRepository.java
  src/main/java/com/issuetracker/domain/milestone/MilestoneService.java
  src/main/java/com/issuetracker/domain/milestone/MilestoneViewMapper.java
  src/main/java/com/issuetracker/domain/milestone/response/MilestoneListResponse.java
  src/main/java/com/issuetracker/domain/milestone/response/MilestoneResponse.java
  src/main/resources/mapper/issue/IssueDetails.xml
  src/main/resources/mapper/milestone/Milestone.xml
  src/test/java/com/issuetracker/domain/milestone/MilestoneControllerTest.java
Labels: feature, 담당: sid

#63 [Fix/#59] 마일스톤, 라벨 수정 로직 변경
  frontend/package-lock.json
  frontend/src/components/milestone/MilestoneAddForm.svelte
  frontend/src/route.svelte
  frontend/src/stores/milestone.js
  frontend/src/utils/validates.js
  src/main/java/com/issuetracker/domain/label/LabelService.java
Labels: fix, 담당: sharpie, 담당: sid

#66 [Feat/#64] 로그인/회원가입 화면 작업
  frontend/package-lock.json
  frontend/package.json
  frontend/public/assets/spring_icon.svg
  frontend/public/assets/svelte_icon.svg
  frontend/public/assets/tailwindcss_icon.svg
  frontend/src/App.svelte
  frontend/src/app.css
  frontend/src/components/auth/LoginForm.svelte
  frontend/src/components/auth/Logo.svelte
  frontend/src/components/auth/RegisterForm.svelte
  frontend/src/components/comment/CommentAddForm.svelte
  frontend/src/components/common/Footer.svelte
  frontend/src/pages/auth/AuthPage.svelte
  frontend/src/route.svelte
  src/main/resources/data.sql
Labels: feature, frontend

#68 Feat/#44 이슈 목록 조회, 이슈 필터링, 이슈 상태 변경 구현
  src/main/java/com/issuetracker/domain/issue/Issue.java
  src/main/java/com/issuetracker/domain/issue/IssueController.java
  src/main/java/com/issuetracker/domain/issue/IssueMapper.java
  src/main/java/com/issuetracker/domain/issue/IssueRepository.java
  src/main/java/com/issuetracker/domain/issue/IssueService.java
  src/main/java/com/issuetracker/domain/issue/IssueViewMapper.java
  src/main/java/com/issuetracker/domain/issue/request/IssueSearchCondition.java
  src/main/java/com/issuetracker/domain/issue/response/IssueCount.java
  src/main/java/com/issuetracker/domain/issue/response/IssueListResponse.java
  src/main/java/com/issuetracker/domain/issue/response/IssuePreviewResponse.java
  src/main/java/com/issuetracker/domain/issue/response/IssueStatusResponse.java
  src/main/java/com/issuetracker/domain/issue/response/SimpleIssue.java
  src/main/java/com/issuetracker/domain/issue/util/IssueQueryParser.java
  src/main/resources/mapper/issue/Issue.xml
  src/main/resources/mapper/issue/SimpleIssue.xml
  src/test/java/com/issuetracker/domain/issue/IssueTest.java
  src/test/java/com/issuetracker/domain/issue/argumentresolver/IssueQueryParserTest.java
  src/test/java/com/issuetracker/domain/member/MemberTest.java
Labels: feature, 담당: sharpie

#70 [Feat/#67] 사이드 바 기능 구현
  frontend/src/app.css
  frontend/src/components/auth/Logo.svelte
  frontend/src/components/common/SideBar.svelte
  frontend/src/components/common/SideBarPopup.svelte
  frontend/src/components/common/SideBarSelectedItems.svelte
  frontend/src/components/issue/IssueItem.svelte
  frontend/src/pages/issue/IssueAddPage.svelte
  frontend/src/pages/issue/IssueDetailPage.svelte
  frontend/src/stores/issue.js
  frontend/src/stores/tags.js
  frontend/src/style/main.css
  src/main/java/com/issuetracker/domain/issue/IssueController.java
  src/main/java/com/issuetracker/domain/issue/request/LabelAssignRequest.java
  src/test/java/com/issuetracker/domain/issue/IssueControllerTest.java
Labels: feature, frontend

#72 [Feat/#71] 마일스톤 화면 작업
  frontend/src/app.css
  frontend/src/components/common/LabelMilestoneNavtab.svelte
  frontend/src/components/issue/IssueItem.svelte
  frontend/src/components/issue/IssueList.svelte
  frontend/src/components/label/LabelEditForm.svelte
  frontend/src/components/label/LabelList.svelte
  frontend/src/components/label/LabelPreview.svelte
  frontend/src/components/milestone/MilestoneAddForm.svelte
  frontend/src/components/milestone/MilestoneEditForm.svelte
  frontend/src/components/milestone/MilestoneList.svelte
  frontend/src/components/milestone/MilestonePreview.svelte
  frontend/src/components/milestone/NoMilestone.svelte
  frontend/src/pages/milestone/MilestonePage.svelte
  frontend/src/stores/milestone.js
  src/main/java/com/issuetracker/domain/milestone/MilestoneController.java
  src/main/java/com/issuetracker/domain/milestone/MilestoneService.java
  src/main/java/com/issuetracker/domain/milestone/MilestoneViewMapper.java
  src/main/resources/mapper/milestone/Milestone.xml
  src/test/java/com/issuetracker/domain/milestone/MilestoneControllerTest.java
Labels: feature, frontend

#73 Feat/#69 담당자 관련 기능 구현 및 프론트 api 연결 작업
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.svelte
  frontend/src/components/auth/LoginForm.svelte
  frontend/src/components/auth/RegisterForm.svelte
  frontend/src/components/common/Header.svelte
  frontend/src/components/common/SideBarPopup.svelte
  frontend/src/components/common/SideBarSelectedItems.svelte
  frontend/src/components/issue/IssueAddForm.svelte
  frontend/src/components/issue/IssueAssignOption.svelte
  frontend/src/components/issue/IssuePreview.svelte
  frontend/src/components/issue/IssueTitleEditForm.svelte
  frontend/src/main.js
  frontend/src/pages/NotFound.svelte
  frontend/src/pages/issue/IssueAddPage.svelte
  frontend/src/pages/issue/IssueDetailPage.svelte
  frontend/src/pages/issue/Issues.svelte
  frontend/src/pages/label/LabelPage.svelte
  frontend/src/pages/milestone/MilestonePage.svelte
  frontend/src/route.svelte
  frontend/src/service/api.js
  frontend/src/stores/auth.js
  frontend/src/stores/issue.js
  frontend/src/stores/label.js
  frontend/src/stores/milestone.js
  frontend/src/stores/tags.js
  src/main/java/com/issuetracker/domain/issue/Assignee.java
  src/main/java/com/issuetracker/domain/issue/Issue.java
  src/main/java/com/issuetracker/domain/issue/IssueController.java
  src/main/java/com/issuetracker/domain/issue/IssueService.java
  src/main/java/com/issuetracker/domain/issue/IssueViewMapper.java
  src/main/java/com/issuetracker/domain/issue/request/IssueCreateRequest.java
  src/main/java/com/issuetracker/domain/issue/request/MemberAssignRequest.java
  src/main/java/com/issuetracker/domain/issue/response/IssueDetails.java
  src/main/java/com/issuetracker/domain/issue/response/IssueDetailsResponse.java
  src/main/java/com/issuetracker/domain/issue/response/IssuePreviewResponse.java
  src/main/java/com/issuetracker/domain/issue/response/SimpleIssue.java
  src/main/java/com/issuetracker/domain/member/AuthController.java
  src/main/java/com/issuetracker/domain/member/MemberController.java
  src/main/java/com/issuetracker/domain/member/MemberRepository.java
  src/main/java/com/issuetracker/domain/member/MemberService.java
  src/main/java/com/issuetracker/domain/member/request/LogInRequest.java
  src/main/java/com/issuetracker/domain/member/response/Auth.java
  src/main/java/com/issuetracker/domain/member/response/MemberListResponse.java
  src/main/java/com/issuetracker/domain/member/response/MemberResponse.java
  src/main/java/com/issuetracker/domain/member/response/SimpleMember.java
  src/main/java/com/issuetracker/domain/milestone/MilestoneService.java
  src/main/java/com/issuetracker/domain/milestone/MilestoneViewMapper.java
  src/main/java/com/issuetracker/domain/milestone/response/MilestoneDetails.java
  src/main/java/com/issuetracker/domain/milestone/response/MilestoneListResponse.java
  src/main/java/com/issuetracker/domain/milestone/response/MilestoneResponse.java
  src/main/java/com/issuetracker/global/config/WebConfig.java
  src/main/java/com/issuetracker/global/security/AuthTokenInterceptor.java
  src/main/java/com/issuetracker/global/security/JwtTokenProvider.java
  src/main/resources/application.yml
  src/main/resources/mapper/issue/IssueDetails.xml
  src/main/resources/mapper/issue/SimpleIssue.xml
  src/main/resources/mapper/milestone/Milestone.xml
  src/main/resources/schema.sql
  src/test/java/com/issuetracker/domain/milestone/MilestoneControllerTest.java
Labels: feature, 담당: sharpie, frontend

#77 [Fix/#76] 사이드바 팝업창 버그 수정
  frontend/src/components/common/SideBar.svelte
  frontend/src/components/common/SideBarPopup.svelte
  frontend/src/components/common/SideBarSelectedItems.svelte
  frontend/src/pages/issue/IssueAddPage.svelte
  frontend/src/route.svelte
  frontend/src/stores/issue.js
  frontend/src/stores/tags.js
Labels: fix

#78 Fix/#75 마일스톤 편집, 댓글 편집, 이슈 편집 삭제, 이슈 열기 닫기, 아이디 유효성 검증
  frontend/src/components/comment/Comment.svelte
  frontend/src/components/comment/CommentAddForm.svelte
  frontend/src/components/comment/CommentEditForm.svelte
  frontend/src/components/milestone/MilestoneEditForm.svelte
  frontend/src/pages/issue/IssueDetailPage.svelte
  frontend/src/stores/issue.js
  src/main/java/com/issuetracker/domain/issue/response/IssueDetailsResponse.java
  src/main/java/com/issuetracker/domain/member/request/LogInRequest.java
  src/main/java/com/issuetracker/domain/member/request/SignUpRequest.java
Labels: fix, bug, 담당: sharpie, frontend

#80 [Feat/#79] 프로필 팝업창 기능 구현
  frontend/src/app.css
  frontend/src/components/auth/LoginForm.svelte
  frontend/src/components/auth/RegisterForm.svelte
  frontend/src/components/common/Header.svelte
  frontend/src/components/common/ProfilePopup.svelte
  frontend/src/stores/auth.js
Labels: feature, frontend

#83 [feat/#82] 팝업창 사용자 경험 개선
  frontend/src/app.css
  frontend/src/components/common/Header.svelte
  frontend/src/components/common/SideBar.svelte
Labels: feature, frontend

#85 [Feat/#74] 댓글 내 이미지 업로드 기능 구현
  frontend/src/pages/issue/IssueDetailPage.svelte
  frontend/src/utils/constants.js
Labels: feature, 담당: sid, frontend

#87 [Feat/#84] 필터 팝업창 기능 및 스켈레톤 화면 구현
  frontend/src/app.css
  frontend/src/components/common/Skeleton.svelte
  frontend/src/components/issue/FilterBar.svelte
  frontend/src/components/issue/FilterBarPopup.svelte
  frontend/src/components/issue/FilterOptions.svelte
  frontend/src/components/issue/IssueList.svelte
  frontend/src/components/issue/IssueLoading.svelte
  frontend/src/components/issue/NoIssue.svelte
  frontend/src/components/milestone/MilestoneList.svelte
  frontend/src/components/part/PopupOption.svelte
  frontend/src/pages/issue/IssueDetailPage.svelte
  frontend/src/stores/filter.js
  frontend/src/stores/issue.js
  src/main/java/com/issuetracker/domain/issue/util/IssueQueryParser.java
Labels: feature, frontend

#86 Fix/#81 로그인 시 한글 아이디 사용 가능하도록 수정, 댓글 편집, 삭제 기능 구현
  frontend/public/assets/profile_icon_duck.svg
  frontend/src/app.css
  frontend/src/components/common/LabelMilestoneNavtab.svelte
  frontend/src/components/common/ProfilePopup.svelte
  frontend/src/components/milestone/MilestonePreview.svelte
  frontend/src/pages/issue/IssueDetailPage.svelte
  frontend/src/stores/auth.js
  frontend/src/stores/issue.js
  frontend/src/stores/label.js
  frontend/src/stores/milestone.js
  src/main/java/com/issuetracker/domain/label/LabelController.java
  src/main/java/com/issuetracker/domain/label/LabelService.java
  src/main/java/com/issuetracker/domain/member/request/LogInRequest.java
  src/main/java/com/issuetracker/domain/member/request/SignUpRequest.java
  src/main/java/com/issuetracker/global/config/WebConfig.java
  src/main/resources/schema.sql
Labels: feature, fix, 담당: sharpie, frontend

#90 [Feat/#88] 마일스톤 날짜 화면 조정 및 이슈 리스트 화면 조정
  frontend/src/components/issue/IssueItem.svelte
  frontend/src/components/issue/IssueList.svelte
  frontend/src/components/milestone/MilestoneAddForm.svelte
  frontend/src/components/milestone/MilestoneEditForm.svelte
  frontend/src/components/milestone/MilestonePreview.svelte
Labels: fix, frontend

#91 [Fix/#89] 댓글 편집 시 기존 이슈 편집 내용 원상복구되던 문제 해결
  frontend/src/pages/issue/IssueDetailPage.svelte
  frontend/src/stores/issue.js
Labels: fix, 담당: sharpie, frontend
